### ISSUE TITLE
Notification Push 기능

### ISSUE THREAD

**Issue by changhwa** [withmate/withmate_destory#37]
특정한 Action이 발생한 후에 사용자 메일 또는 쪽지 등으로
알림을 보내는 방법이 필요합니다.
해당 서비스는 공통적으로 관리되어야 합니다. 
( 여러군데에서 사용될 수 있음 )
#### ToDo
1. [x] SMTP를 이용한 테스트 메일을 발송한다.
2. [x] #8 이슈를 참고하여 Async 테스트 소스를 구현한다
3. [x] 사용자에게 메일을 발송한다.
4. [ ] 템플릿을 만든다.
5. [ ] Project 등록시 담당자에게 메일을 발송한다.
6. [ ] Project 수정시 담당자에게 메일을 발송한다.
7. [ ] Project 삭제시 담당자에게 메일을 발송한다.

**Comment by changhwa** [comment]
이 기능 제가 구현하겠습니다..

**Comment by changhwa** [comment]
굳이 시간낭비 없이 구현되어있는 메일 플러그인을 활용하겠습니다.
1. http://grails.org/plugin/asynchronous-mail
2. http://grails.org/plugin/mail

둘 테스트 해보고 결정토록 하겠습니다.

**Comment by changhwa** [comment]
Project 에 관련한 발송은 프로젝트 리펙토링에서 포함시키겠습니다.
